import type { Metadata } from 'next'
import { Jost } from 'next/font/google'
import './globals.css'


import Header from '@/components/header/header'
import Footer from '@/components/footer'

const jostSansSerif = Jost({
  weight: '400',
	variable: '--font-jost',
	subsets: ['latin'],
})


export const metadata: Metadata = {
	title: 'Elements Hotel template',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='pl'>
			<body className={`${jostSansSerif.variable}  antialiased`}>
				<Header />

				{children}
				<Footer />
			</body>
		</html>
	)
}
